-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cidade
(
    id bigint NOT NULL,
    cep character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    estado_id bigint,
    CONSTRAINT cidade_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id bigint NOT NULL,
    bairro character varying(255) COLLATE pg_catalog."default",
    cpf character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    endereco character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    telefone character varying(255) COLLATE pg_catalog."default",
    cidade_id bigint,
    CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estado
(
    id bigint NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default",
    sigla character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT estado_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fornecedor
(
    id bigint NOT NULL,
    bairro character varying(255) COLLATE pg_catalog."default",
    cnpj character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    endereco character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    telefone character varying(255) COLLATE pg_catalog."default",
    cidade_id bigint,
    CONSTRAINT fornecedor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.funcionario
(
    id bigint NOT NULL,
    bairro character varying(255) COLLATE pg_catalog."default",
    cargo character varying(255) COLLATE pg_catalog."default",
    cpf character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    endereco character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    telefone character varying(255) COLLATE pg_catalog."default",
    cidade_id bigint,
    CONSTRAINT funcionario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.produto
(
    id bigint NOT NULL,
    codigo_barras character varying(255) COLLATE pg_catalog."default",
    estoque double precision,
    lucro double precision,
    nome character varying(255) COLLATE pg_catalog."default",
    preco_custo double precision,
    preco_venda double precision,
    unidade_medida character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT produto_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cidade
    ADD CONSTRAINT fkkworrwk40xj58kevvh3evi500 FOREIGN KEY (estado_id)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT fkc2150e1t4hbr2owxjx1smbcwc FOREIGN KEY (cidade_id)
    REFERENCES public.cidade (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fornecedor
    ADD CONSTRAINT fkm48tyyp54y2l1ei7ubq2t27wt FOREIGN KEY (cidade_id)
    REFERENCES public.cidade (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionario
    ADD CONSTRAINT fkhoqxa81f767jcril4vbc8d2rg FOREIGN KEY (cidade_id)
    REFERENCES public.cidade (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;